### ISSUE TITLE
project is not a git lfs repo

### ISSUE THREAD

**Issue by nweeden** [S2-/gitlit#1]
Getting the folllowing error when trying to run on a git repo with lfs enabled:
C:\\GitHub\Project is not a git lfs **repo.**

  If I run 'git lfs ls-files' directly from the command line in the project folder it works fine.

![image](https://user-images.githubusercontent.com/15108484/49813692-e590e980-fd5f-11e8-93da-bfa4af5dab12.png)

**Comment by 5im-0n** [comment]
Thanks, can you maybe share the repo so I can reproduce the problem locally?

**Comment by nweeden** [comment]
I'm not sure I can really, it's for an ongoing commercial project.  I can give you some more information about the system though.  We're running Git LFS 2.3.4 and Git 2.16.0.2 on Windows 10.  The repo is connected to GitHub.  I've also just run it on a smaller project and it works on that.  It may be because it's got 5384 files and is 31.1GB in size (it's an Unreal project).

**Comment by 5im-0n** [comment]
I have to check if I can somehow reproduce the error so I can debug it.

**Comment by 5im-0n** [comment]
Maybe you can help? I think the error gets thrown somewhere here:
https://github.com/S2-/gitlit/blob/master/app/main.js#L15

**Comment by 5im-0n** [comment]
I tried to increase the maxBuffer on the exec calls:
https://github.com/S2-/gitlit/commit/613525752bef69cd1da4ca3259fa5d66d3b24802
and made a new release:
https://github.com/S2-/gitlit/releases/tag/v1.0.3

Let me know.

**Comment by nweeden** [comment]
Thanks for the quick response, I'm not really a JS person so not sure I can specifically help regarding the workings of it.  I've tested the new release though and it's thrown a different error now:

![image](https://user-images.githubusercontent.com/15108484/49860962-b8414b80-fdf2-11e8-8ab7-18732a4670bc.png)

**Comment by 5im-0n** [comment]
https://github.com/S2-/gitlit/releases/tag/v1.0.4 should fix this.

Let me know!
