### ISSUE TITLE
Error while retrieving locks

### ISSUE THREAD

**Issue by csrichter** [S2-/gitlit#2]
the GUI shows: "C:\workspace\gitlabsandbox is not a git lfs repo."
console prints:

    { Error: Command failed: git lfs locks
    Error while retrieving locks: exit status 255
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12) killed: false, code: 2, signal: null, cmd: 'git lfs locks' 
    }

git lfs ls-files:

    2cde2a0fae * lfs-test/MagicUltimateTest - CANopen Magic Ultimate 03.05.2019 13_28_50_hb.m4v
    c6f147c62e * lfs-test/filelock-test.docx

might be related to #1

i'm using git version 2.21.0.windows.1
on windows 10 pro 1709

**Comment by csrichter** [comment]
interesting...

if i use powershell to run "git lfs locks" it produces an error:

    PS C:\workspace\gitlabsandbox> git lfs locks
    Error while retrieving locks: exit status 255

but if i use git bash it works:

    c.richter@LATI-417 MINGW64 /c/workspace/gitlabsandbox (UserStory/filelocking)
    $ git lfs locks

**Comment by 5im-0n** [comment]
Seems like a git lfs misconfiguration.
What does `git lfs locks` return in cmd?

**Comment by csrichter** [comment]
sorry for the late reply
it returns the same as in powershell

    C:\workspace\gitlabsandbox>git lfs locks
    Error while retrieving locks: exit status 255

**Comment by csrichter** [comment]
i think the problem is SSH authentication
If i use gitlit on a repository checked out via HTTPS it works perfectly

**Comment by 5im-0n** [comment]
gitlit just uses git from your system, so if it works with git it should work in gitlit.
What git server are you using?

**Comment by csrichter** [comment]
> gitlit just uses git from your system, so if it works with git it should work in gitlit.

it doesn't work with git, if startet via cmd or powershell.
I assume that's because the SSH keys are not configured properly in that environment

in "git bash" the SSH keys are configured, so git (and by extension gitlit) work properly

this is a problem with my git config and not gitlit (although the provided error message could be better)

**Comment by 5im-0n** [comment]
Thanks for the feedback!
