### ISSUE TITLE
It says repo is not a git lfs repo.

### ISSUE THREAD

**Issue by ponyportal2** [S2-/gitlit#6]
It says repo is not a git lfs repo. Though I have gitlfs files in it for sure. All files should be gitlfs for it to work? What should I change for it to start working?

**Comment by 5im-0n** [comment]
Are you on Windows or Linux? Does `git ls-files | git check-attr --stdin lockable` in your repo dir return something?

**Comment by ponyportal2** [comment]
> 
> 
> Are you on Windows or Linux? Does `git ls-files | git check-attr --stdin lockable` in your repo dir return something?

I'm using Windows. Thanks! It showed what the problem is. I just needed to add "lockable" at the end of the line in .gitattributes to my lfs-tracked file types. I know it's another matter, but by the way - having a way to lock an entire directory and having a directory view would be great! :) Also having an auto-refresh and notifications when someone unlocked the file. I'm using these locks for game development purposes and they can be very helpful. It can revolutionize the workflow for some jobs. I know it's not an issue, just a feature requests. Thank you!
